# -----------------------------------------------------------------------------
# LEGACY / AD-HOC SCRIPT
# Kept for transparency: this is one of the helper scripts used during the
# original city runs of the study. It is not part of the supported CLI.
#
# ALL FILE PATHS AND DEFAULTS BELOW ARE EXAMPLES FROM THOSE RUNS.
# No data ships with this repository: replace every path with a link to your
# own data before running, either by editing the constants/defaults in this
# file or by passing the corresponding command-line arguments.
# -----------------------------------------------------------------------------

import numpy as np
import rasterio

# Path to the delta raster generated by your scenario script
delta_path = "results_greening_demo/delta_LST.tif"

with rasterio.open(delta_path) as src:
    delta = src.read(1)
    # Calculate mean ignoring NaNs (areas outside city/mask)
    mean_change = np.nanmean(delta)

print(f"City-Wide Mean LST Decrease: {-mean_change:.4f} °C")